repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: '^.+.html'
-   repo: local
    hooks:
    -   id: build
        name: build
        language: script
        entry: ./build.sh
